Webapp/Webapp/Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Webapp.Converters;
using Webapp.Interfaces;
using Webapp.Models;
using Webapp.Models.Data;
using Webapp.Repository;

namespace Webapp.Controllers
{
    /// <summary>
    /// Doctor controller
    /// </summary>
    [Authorize(Roles = "doctor, admin")]
    public class DoctorController : BaseController
    {
        // Repos
        private readonly DoctorRepository doctorRepository;
        private readonly AccountRepository accountRepository;
        private readonly DepartmentRepository departmentRepository;
        // Converter
        private readonly DoctorViewModelConverter converter = new DoctorViewModelConverter();

        public DoctorController
            (
                DoctorRepository doctorRepository,
                AccountRepository accountRepository,
                DepartmentRepository departmentRepository
            )
        {
            this.doctorRepository = doctorRepository;
            this.accountRepository = accountRepository;
            this.departmentRepository = departmentRepository;
        }

        /// <summary>
        /// Page list of doctors
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            DoctorViewModel vm = new DoctorViewModel();
            List<Doctor> doctors = new List<Doctor>();
            if (User.IsInRole("admin"))
            {
                // Retrieve doctors
                doctors = doctorRepository.GetAll();
                if (doctors.Count < 1)
                    return View();
            }
            else if(User.IsInRole("doctor"))
            {
                long userId = GetUserId();
                doctors = doctorRepository.GetByDoctorWithDepartment(userId);
                if (doctors.Count < 1)
                    return View();
            }
            
            // Convert to viewmodels
            vm.Doctors = converter.ModelsToViewModel(doctors);
            //foreach(Doctor doctor in doctors)
            //{
            //    UserAccount account = accounts.FirstOrDefault(a => a.DoctorId == doctor.Id);
            //    if (account == null)
            //    {
            //        continue;
            //    }

            //    doctor.Name = account.Name;
            //    vm.Doctors.Add(converter.ModelToViewModel(doctor));
            //}
            
            return View(vm);
        }

        /// <summary>
        /// Detail page for doctor
        /// </summary>
        /// <param name="id">Id filter</param>
        /// <returns></returns>
        public IActionResult Details(long id)
        {
            // Check if id is set
            if (id < 1)
                return BadRequest("Id cannot be 0");

            // Retrieve doctor
            Doctor doctor = doctorRepository.GetById(id);
            if (doctor == null)
                return BadRequest("Department could not be found");

            // Convert to viewmodel and return in view
            DoctorDetailViewModel vm = converter.ModelToViewModel(doctor);
            return View(vm);
        }

        /// <summary>
        /// Get for create
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            DoctorDetailViewModel vm = new DoctorDetailViewModel();
            vm.Genders = converter.GetGenders();
            return View(vm);
        }

        /// <summary>
        /// Post for create doctor
        /// </summary>
        /// <param name="model">Model to insert</param>
        /// <returns></returns>
        [HttpPost]
        [Authorize(Roles = "admin")]
        public IActionResult Create(DoctorDetailViewModel vm)
        {
            // Check if model is valid
            if (ModelState.IsValid)
            {
                Doctor doctor = converter.ViewModelToModel(vm);
                long id = doctorRepository.Insert(doctor);
                return RedirectToAction("Details", new { id });
            }
            else
            {
                vm.Genders = converter.GetGenders();
                return View();
            }
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult Edit(long id)
        {
            if (id < 1)
                return BadRequest("Id cannot be 0");

            Doctor doctor = doctorRepository.GetById(id);
            if (doctor == null)
                return BadRequest("Department could not be found");

            DoctorDetailViewModel vm = converter.ModelToViewModel(doctor);
            return View(vm);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public IActionResult Edit(long id, DoctorDetailViewModel vm)
        {
            if (ModelState.IsValid)
            {
                if (id != vm.EmployeeNumber)
                {
                    return BadRequest("Ids do not match");
                }

                Doctor doctor = converter.ViewModelToModel(vm);

                if (doctorRepository.Update(doctor))
                {
                    return RedirectToAction("Details", new { doctor.Id });
                }
                else
                {
                    vm.Genders = converter.GetGenders();
                    return View(vm);
                }
            }
            else
            {
                vm.Genders = converter.GetGenders();
                return View(vm);
            }
        }

        [Authorize(Roles = "admin")]
        public IActionResult Delete(long id)
        {

            if (ModelState.IsValid)
            {
                if (!departmentRepository.Delete(id))
                    return BadRequest("Something went wrong deleting object");
            }
            return RedirectToAction("Index");
        }
    }
}

Webapp/Webapp/Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Webapp.Context;
using Webapp.Converters;
using Webapp.Interfaces;
using Webapp.Models;
using Webapp.Models.Data;
using Webapp.Repository;

namespace Webapp.Controllers
{
    /// <summary>
    /// Controller for patient
    /// </summary>
    public class PatientController : BaseController
    {
        // Repos
        private readonly PatientRepository patientRepository;
        private readonly TreatmentRepository treatmentRepository;
        private readonly TreatmentTypeRepository treatmentTypeRepository;
        private readonly CommentRepository commentRepository;

        // Converters
        private readonly PatientWithTreatmentsViewModelConverter patientWithTreatmentsVMC = new PatientWithTreatmentsViewModelConverter();
        private readonly TreatmentViewModelConverter treatmentVMC = new TreatmentViewModelConverter();
        private readonly PatientViewModelConverter patientVMC = new PatientViewModelConverter();

        /// <summary>
        /// Default constructor for patient controller
        /// </summary>
        /// <param name="patientRepository"></param>
        /// <param name="treatmentRepository"></param>
        public PatientController(   
            PatientRepository patientRepository, 
            TreatmentRepository treatmentRepository,
            TreatmentTypeRepository treatmentTypeRepository,
            CommentRepository commentRepository
            )
        {
            this.patientRepository = patientRepository;
            this.treatmentRepository = treatmentRepository;
            this.treatmentTypeRepository = treatmentTypeRepository;
            this.commentRepository = commentRepository;
        }

        /// <summary>
        /// Gets all patients of a doctor and converts them from a class to a viewmodel
        /// </summary>
        [Authorize(Roles= "doctor")]
        public IActionResult Index()
        {
            // Retrieve and convert all - active - patients
            List<Patient> patienten = patientRepository.GetAll();
            List<PatientListViewModel> vms = patientVMC.PatientlistToViewModel(patienten);

            return View(vms);
        }

        /// <summary>
        /// Gets a treatment with a small amount of data of the patient with the given id and converts that to a viewmodel
        /// </summary>
        //[HttpGet("{id}")]
        [Authorize(Roles = "doctor, patient")]
        public IActionResult Treatment(long id)
        {
            
            PatientDetailViewModel patientDetailViewModel = new PatientDetailViewModel();
            Patient patient = new Patient();
            try
            {
                if (User.IsInRole("doctor"))
                {
                    patient = patientRepository.GetById(id);
                    patient.Treatments = treatmentRepository.GetByPatient(id);
                }
                else if(User.IsInRole("patient"))
                {
                    long patientId = patientRepository.GetPatientIdByTreatmentId(id);
                    patient = patientRepository.GetById(patientId);
                    patient.Treatments = treatmentRepository.GetByPatient(patientId);
                }
                    foreach (Treatment t in patient.Treatments)
                    {
                        t.TreatmentType = treatmentTypeRepository.GetByTreatmentId(t.TreatmentTypeId);
                    }
                

                patientDetailViewModel = patientWithTreatmentsVMC.PatientToViewModel(patient);
            }
            catch (Exception Ex)
            {
                return BadRequest(Ex.Message);
            }
            return View(patientDetailViewModel);
        }

        [Authorize(Roles = "doctor")]
        [HttpPost]
        public IActionResult Treatment(long id, PatientDetailViewModel vm)
        {
            Comment comment = vm.TreatmentDetailViewModels[0].Description;
            comment.TreatmentId = id;
            commentRepository.Insert(comment);
            return RedirectToAction("index", "patient");
        }
    }
}

Webapp/Webapp/Controllers/TreatmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Webapp.Context;
using Webapp.Converters;
using Webapp.Interfaces;
using Webapp.Models;
using Webapp.Models.Data;
using Webapp.Repository;

namespace Webapp.Controllers
{
    /// <summary>
    /// Treatment controller
    /// </summary>
    [Authorize(Roles = "doctor, patient")]
    public class TreatmentController : BaseController
    {
        /// <summary>
        /// Repos
        /// </summary>
        private readonly TreatmentRepository treatmentRepository;
        private readonly PatientRepository patientRepository;
        private readonly TreatmentTypeRepository treatmentTypeRepository;
        private readonly CommentRepository commentRepository;

        /// <summary>
        /// Converters
        /// </summary>
        private readonly TreatmentViewModelConverter TreatmentConverter = new TreatmentViewModelConverter();
        private readonly PatientViewModelConverter PatientConverter = new PatientViewModelConverter();
        private readonly TreatmentTypeViewModelConverter TypeConverter = new TreatmentTypeViewModelConverter();

        /// <summary>
        /// Default constructor
        /// </summary>
        /// <param name="treatmentRepository"></param>
        /// <param name="patientRepository"></param>
        /// <param name="treatmentTypeRepository"></param>
        public TreatmentController(
            TreatmentRepository treatmentRepository, 
            PatientRepository patientRepository, 
            TreatmentTypeRepository treatmentTypeRepository,
            CommentRepository commentRepository
            )
        {
            this.treatmentRepository = treatmentRepository;
            this.patientRepository = patientRepository;
            this.treatmentTypeRepository = treatmentTypeRepository;
            this.commentRepository = commentRepository;
        }

        /// <summary>
        /// Page of treatment detail
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            // Get by role
            List<Treatment> items = new List<Treatment>();
            if (User.IsInRole("doctor"))
            {
                items = treatmentRepository.GetByDoctor(GetUserId());
                
            }
            else if (User.IsInRole("patient"))
            {
                items = treatmentRepository.GetByPatient(GetUserId());
            }

            // Parse to viewmodel
            TreatmentViewModel vm = new TreatmentViewModel()
            {
                treatments = new List<TreatmentDetailViewModel>()
            };
            // add treatments
            foreach (Treatment treatment in items)
            {
                vm.treatments.Add(TreatmentConverter.ModelToViewModel(treatment));
            }

            // Return view with treatments
            return View(vm.treatments);
        }

        /// <summary>
        /// Add new treatment
        /// </summary>
        /// <param name="id"> PatientId </param>
        /// <returns></returns>
        [Authorize(Roles = "doctor")]
        [HttpGet]
        public IActionResult Create(long id = 0)
        {
            // Get and convert treatment
            TreatmentDetailViewModel vm = new TreatmentDetailViewModel
            {
                Patients = PatientConverter.PatientlistToViewModel(patientRepository.GetAll()),
                TreatmentTypes = TypeConverter.ModelsToViewModel(treatmentTypeRepository.GetAll()),
                PatientId = id
            };
            return View(vm);
        }

        /// <summary>
        /// Add treatment
        /// </summary>
        /// <param name="vm"></param>
        /// <returns></returns>
        [Authorize(Roles = "doctor")]
        [HttpPost]
        public IActionResult Create(TreatmentDetailViewModel vm)
        {
            // Convert back and create treatment
            Treatment treatment = TreatmentConverter.ViewModelToModel(vm);
            treatment.DoctorId = GetUserId();
            Comment comment = vm.Description;
            comment.TreatmentId = treatmentRepository.Insert(treatment);
            commentRepository.Insert(comment);
            return RedirectToAction("index", "treatment");
        }

        /// <summary>
        /// Get for update
        /// </summary>
        /// <param name="id"> TreatmentId </param>
        /// <returns></returns>
        [Authorize(Roles = "doctor")]
        [HttpGet]
        public IActionResult Edit(long id)
        {
            //Retrieve treatment
            TreatmentDetailViewModel vm = TreatmentConverter.ModelToViewModel(treatmentRepository.GetById(id));
            vm.PatientName = patientRepository.GetById(vm.PatientId).Name;
            vm.TreatmentTypes = TypeConverter.ModelsToViewModel(treatmentTypeRepository.GetAll());

            // Return with model
            return View(vm);
        }

        /// <summary>
        /// Post update treatment
        /// </summary>
        /// <param name="id"></param>
        /// <param name="vm"></param>
        /// <returns></returns>
        [Authorize(Roles = "doctor")]
        [HttpPost]
        public IActionResult Edit(long id, TreatmentDetailViewModel vm)
        {
            Treatment treatment = TreatmentConverter.ViewModelToModel(vm);
            treatmentRepository.Update(treatment);
            return RedirectToAction("index", "treatment");
        }
    }
}

Webapp/Webapp/Views/Home/Dashboard.cshtml
@{
    ViewData["Title"] = "Dashboard";
}
<link rel="stylesheet" href="~/css/button.css" />
<form>
    <div class="container col-md-12" id="buttons">
        @if (Context.User.IsInRole("admin"))
        {
                    <h2><i class="fa fa-hospital-o fa-lg"></i> Afdelingen</h2>
                    <div class="list-group-horizontal row">
                        <button class="btn btn-lg" asp-action="Index" asp-controller="Department">Overzicht</button>
                        <button class="btn btn-lg" asp-action="Create" asp-controller="Department">Nieuwe toevoegen</button>
                    </div>
                    <h2><i class="fa fa-heartbeat fa-lg"></i> Type behandelingen</h2>
                    <div class="list-group-horizontal row">
                        <button class="btn btn-lg" asp-action="Index" asp-controller="TreatmentType">Overzicht</button>
                        <button class="btn btn-lg" asp-action="Create" asp-controller="TreatmentType">Nieuwe toevoegen</button>
                    </div>
                    <h2><i class="fa fa-user-md fa-lg"></i> Artsen</h2>
                    <div class="list-group-horizontal row">
                        <button class="btn btn-lg" asp-action="Index" asp-controller="Doctor">Overzicht</button>
                        <button class="btn btn-lg" asp-action="Create" asp-controller="Doctor">Nieuwe toevoegen</button>
                    </div>
        }
        else if (Context.User.IsInRole("doctor"))
        {
                    <h2><i class="fa fa-medkit fa-lg"></i> Behandelingen</h2>
                    <div class="list-group-horizontal row">
                        <button class="btn btn-lg" asp-action="Index" asp-controller="Treatment">Overzicht</button>
                        <button class="btn btn-lg" asp-action="Create" asp-controller="Treatment">Nieuwe toevoegen</button>
                    </div>
                    <h2><i class="fa fa-bed fa-lg"></i> Patiënten</h2>
                    <div class="list-group-horizontal row">
                        <button class="btn btn-lg" asp-action="Index" asp-controller="Patient">Overzicht</button>
                    </div>
                    <h2><i class="fa fa-hospital-o fa-lg"></i> Afdelingen</h2>
                    <div class="list-group-horizontal row">
                        <button class="btn btn-lg" asp-action="Index" asp-controller="Department">Overzicht</button>
                    </div>
        }
        else if (Context.User.IsInRole("patient"))
        {
            <h2><i class="fa fa-medkit fa-lg"></i> Behandelingen</h2>
            <div class="list-group-horizontal row">
                <button class="btn btn-lg" asp-action="Index" asp-controller="Treatment">Overzicht</button>
            </div>
        }
    </div>
</form>

Webapp/Webapp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = null;
}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Webapp</title>
    <link rel="stylesheet" href="~/css/login.css" />
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
    <!------ Include the above in your HEAD tag ---------->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<body>
    <div class="grandParentContainer">
        <div class="parentContainer">
            <div align="center">
                <form class="loginForm" id="loginForm" method="post">
                    <h2>LOGIN</h2>
                    <div class="form-group">

                        <label for="username" class="col-sm-3 control-label">username </label>
                        <div class="col-sm-9">
                            <input type="text" id="username" placeholder="username" class="form-control" name="username">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="password" class="col-sm-3 control-label">Password</label>
                        <div class="col-sm-9">
                            <input type="password" id="password" placeholder="Password" class="form-control" name="password" value="Test123!">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary btn-block" asp-action="Login">Login</button>
                </form> <!-- /form -->
            </div>
        </div>
    </div>
</body>
    

Webapp/Webapp/Views/Home/Logout.cshtml
@{
    ViewData["Title"] = "Logout";
}

<h2>Logout</h2>

U bent succesvol uitgelogd!